version: '3.8'
services:
  webrtc-build:
    build: .
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: bash -c "cd examples && cargo build --release --example vtk-cube-client-console"
    environment:
      - RUST_BACKTRACE=1
